spring:
  datasource:
    url: jdbc:h2:mem:${random.uuid};DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: info